from pathlib import Path

root = Path('/home/ubuntu/jourthon_static_site')
services_path = root / 'services.html'
style_path = root / 'style.css'
html = services_path.read_text(encoding='utf-8')

new_main = '''<header class="page-hero"><div class="page-hero-bg" style="background-image:url('images/service_supplychain.jpg')"></div><div class="page-hero-content"><div class="eyebrow reveal"><span class="dot"></span>What We Do</div><h1 class="page-title reveal">Six capabilities. <em>One seamless partner.</em></h1><p class="page-subtitle reveal">From scientific formulation and regulatory compliance to contract manufacturing, packaging, design, and market entry — Jourthon supports every step of the supplement lifecycle while preserving the original service content.</p><div class="service-anchor-nav reveal"><a href="#contract-manufacturing">01 Manufacturing</a><a href="#design-labelling">02 Design & Labelling</a><a href="#nutritional-supplements">03 Product Portfolio</a><a href="#packaging">04 Packaging</a><a href="#regulatory-compliance">05 Compliance</a><a href="#research-development">06 R&D</a></div></div></header>
<section id="contract-manufacturing" class="service-module"><div class="container service-row "><div class="service-text reveal"><span class="tag">01 — Contract Manufacturing</span><h2>World-Class Contract Manufacturing</h2><p class="lead">From raw material to finished product — under one coordinated program.</p><p class="section-subtitle">Jourthon works through qualified manufacturing resources across North America and coordinates the production process from sourcing and dosage-form selection to final packaging and release preparation.</p><ul class="mini-list"><li>Softgel and hard capsule encapsulation</li><li>Tablet compression and coating</li><li>Gummy and chewable manufacturing</li><li>Powder blending and sachet filling</li><li>Liquid and tincture production</li><li>Private label and white label options</li></ul><div class="service-badges"><span>GMP-Oriented</span><span>Quality Controlled</span><span>Private Label Ready</span></div><a class="btn-light" href="contact.html#inquiry">Get a Quote for This Service</a></div><div class="service-img reveal"><img src="images/service_formulation.jpg" alt="Contract Manufacturing"></div></div></section>
<section id="design-labelling" class="service-module"><div class="container service-row reverse"><div class="service-text reveal"><span class="tag">02 — Design & Labelling</span><h2>Packaging Design That Sells</h2><p class="lead">Compliant labels. Premium aesthetics. Market-ready identity.</p><p class="section-subtitle">This section was compressed in the first revision, so it has now been restored closer to the original. Jourthon can support brand identity, label design, supplement facts formatting, bilingual label requirements, and print-ready handoff for packaging vendors.</p><ul class="mini-list"><li>Brand identity and logo development</li><li>Label design for front, back, and side panels</li><li>Health Canada NPN / DIN label compliance support</li><li>FDA supplement facts panel formatting</li><li>Packaging structure design for bottles, pouches, and boxes</li><li>Print-ready file preparation and vendor coordination</li></ul><div class="service-badges"><span>Health Canada Aligned</span><span>FDA-Oriented</span><span>Print-Ready Output</span></div><a class="btn-light" href="contact.html#inquiry">Get a Quote for This Service</a></div><div class="service-img reveal"><img src="images/cta_bg.jpg" alt="Design and labelling"></div></div></section>
<section id="nutritional-supplements" class="service-module product-portfolio-section"><div class="container"><div class="section-header"><div><div class="section-kicker reveal">03 — Nutritional Supplements</div><h2 class="section-title reveal">A complete supplement <em>product portfolio</em></h2></div><p class="section-subtitle reveal">The original Services page included a broad product-category section. It is now restored as a dedicated portfolio block so visitors can quickly see the types of products Jourthon can help develop, manufacture, package, and launch.</p></div><div class="product-portfolio-grid reveal"><article class="product-chip"><span>Vitamins & Minerals</span></article><article class="product-chip"><span>Omega-3 & Fish Oil</span></article><article class="product-chip"><span>Probiotics & Prebiotics</span></article><article class="product-chip"><span>Sports Nutrition</span></article><article class="product-chip"><span>Weight Management</span></article><article class="product-chip"><span>Immune Support</span></article><article class="product-chip"><span>Beauty & Collagen</span></article><article class="product-chip"><span>Brain & Cognitive</span></article><article class="product-chip"><span>Sleep & Stress</span></article><article class="product-chip"><span>Herbal & Botanicals</span></article><article class="product-chip"><span>Children's Health</span></article><article class="product-chip"><span>Senior Wellness</span></article></div><div class="portfolio-note reveal"><strong>Every category. Every format. Every market segment.</strong><p>Jourthon can help position these categories across common dosage forms such as capsules, softgels, tablets, gummies, powders, liquids, sachets, and tinctures.</p><a class="btn-light" href="contact.html#inquiry">Discuss Product Category</a></div></div></section>
<section id="packaging" class="service-module"><div class="container service-row reverse"><div class="service-text reveal"><span class="tag">04 — Packaging</span><h2>End-to-End Packaging Solutions</h2><p class="lead">Protect your product. Elevate your brand.</p><p class="section-subtitle">Packaging is more than a container — it is a brand statement and a compliance requirement. Jourthon coordinates packaging components that balance product protection, shelf presentation, regulatory needs, and cost efficiency.</p><ul class="mini-list"><li>HDPE and PET bottles in multiple sizes</li><li>Blister packs and clamshells</li><li>Stand-up pouches and sachets</li><li>Folding cartons and display boxes</li><li>Child-resistant and senior-friendly closures</li><li>Eco-friendly and sustainable packaging options</li></ul><div class="service-badges"><span>Sustainable Options</span><span>Custom MOQ</span><span>Shelf-Ready</span></div><a class="btn-light" href="contact.html#inquiry">Get a Quote for This Service</a></div><div class="service-img reveal"><img src="images/service_supplychain.jpg" alt="Packaging solutions"></div></div></section>
<section id="regulatory-compliance" class="service-module"><div class="container service-row "><div class="service-text reveal"><span class="tag">05 — Regulatory & Compliance</span><h2>Navigate Regulations with Confidence</h2><p class="lead">Health Canada. FDA. Global market entry — coordinated with a compliance-first mindset.</p><p class="section-subtitle">Regulatory compliance is one of the most complex parts of bringing a health supplement to market. Jourthon helps organize the pathway, label review, product documentation, and submission-related preparation for North American and selected global market needs.</p><ul class="mini-list"><li>NPN Natural Product Number application coordination</li><li>DIN Drug Identification Number registration support</li><li>FDA DSHEA compliance review support</li><li>Product license applications and renewals coordination</li><li>Site license coordination</li><li>Export compliance for EU, Australia, and Asia-Pacific planning</li><li>Adverse reaction reporting and post-market surveillance process support</li></ul><div class="service-badges"><span>Health Canada Focus</span><span>FDA-Oriented</span><span>Global Export Ready</span></div><a class="btn-light" href="contact.html#inquiry">Get a Quote for This Service</a></div><div class="service-img reveal"><img src="images/service_compliance.jpg" alt="Regulatory compliance"></div></div></section>
<section id="research-development" class="service-module"><div class="container service-row reverse"><div class="service-text reveal"><span class="tag">06 — Research & Development</span><h2>Science-Driven Formulation Innovation</h2><p class="lead">Evidence-based formulas designed for efficacy and market success.</p><p class="section-subtitle">Jourthon supports formula development and optimization by connecting nutritional science, ingredient sourcing, stability considerations, and market positioning into a practical product development plan.</p><ul class="mini-list"><li>Custom formula development from concept</li><li>Existing formula optimization and reformulation</li><li>Ingredient sourcing and supplier qualification</li><li>Stability testing and shelf-life study coordination</li><li>Clinical literature review and efficacy substantiation</li><li>Non-GMO, vegan, and halal formulation considerations</li></ul><div class="service-badges"><span>Non-GMO Options</span><span>Vegan-Friendly</span><span>Halal-Oriented</span></div><a class="btn-light" href="contact.html#inquiry">Get a Quote for This Service</a></div><div class="service-img reveal"><img src="images/service_market.jpg" alt="Research and development"></div></div></section>
<section class="cta"><div class="cta-bg" style="background-image:url('images/cta_bg.jpg')"></div><div class="container reveal"><h2>Ready to build your product?</h2><p>Share your product category, dosage form, target market, and launch stage. Jourthon will help identify the right service path.</p><div class="cta-actions"><a class="btn-primary" href="contact.html#inquiry">Submit Product Brief</a><a class="btn-secondary" href="quality.html">View Quality Standards</a></div></div></section>'''

start = html.index('<header class="page-hero">')
end = html.index('<footer>')
html = html[:start] + new_main + html[end:]
services_path.write_text(html, encoding='utf-8')

css_add = '''\n/* Restored original Services page content */\n.service-anchor-nav{display:flex;flex-wrap:wrap;gap:10px;margin-top:30px;max-width:860px}.service-anchor-nav a{display:inline-flex;padding:9px 14px;border-radius:999px;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.28);color:rgba(255,255,255,.92);font-size:12px;font-weight:800;letter-spacing:.04em;backdrop-filter:blur(8px)}.service-anchor-nav a:hover{background:rgba(255,255,255,.2);color:var(--white)}.service-badges{display:flex;flex-wrap:wrap;gap:10px;margin:22px 0 24px}.service-badges span{display:inline-flex;padding:8px 12px;border-radius:999px;background:linear-gradient(135deg,rgba(46,125,209,.12),rgba(0,200,224,.12));border:1px solid rgba(46,125,209,.18);color:var(--blue-light);font-size:12px;font-weight:800}.product-portfolio-section{background:var(--off-white)}.product-portfolio-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.product-chip{background:var(--white);border:1px solid var(--gray-light);border-radius:18px;padding:22px;box-shadow:var(--shadow-soft);transition:all var(--transition);min-height:94px;display:flex;align-items:center}.product-chip:hover{transform:translateY(-4px);box-shadow:var(--shadow-card);border-color:rgba(46,125,209,.3)}.product-chip span{font-weight:850;color:var(--navy);line-height:1.35}.product-chip:before{content:'';width:9px;height:9px;border-radius:50%;background:linear-gradient(135deg,var(--blue-light),var(--cyan));box-shadow:0 0 0 6px rgba(0,200,224,.1);margin-right:14px;flex:0 0 auto}.portfolio-note{margin-top:28px;background:var(--white);border:1px solid var(--gray-light);border-radius:var(--radius-lg);padding:28px;box-shadow:var(--shadow-card);display:grid;gap:10px}.portfolio-note strong{font-size:20px;color:var(--navy)}.portfolio-note p{font-size:15px;line-height:1.72;color:var(--text-mid);max-width:760px}@media (max-width:980px){.product-portfolio-grid{grid-template-columns:repeat(2,1fr)}}@media (max-width:640px){.service-anchor-nav{display:none}.product-portfolio-grid{grid-template-columns:1fr}.product-chip{min-height:auto}}\n'''
css = style_path.read_text(encoding='utf-8')
if 'Restored original Services page content' not in css:
    style_path.write_text(css + css_add, encoding='utf-8')

# mirror edits into deploy package if it exists
package = Path('/home/ubuntu/jourthon_deploy_package')
if package.exists():
    (package / 'services.html').write_text(services_path.read_text(encoding='utf-8'), encoding='utf-8')
    (package / 'style.css').write_text(style_path.read_text(encoding='utf-8'), encoding='utf-8')

print('Restored Services page content, including original 12 supplement categories.')
